# countries.py - Country list for AppGrowth bot

POPULAR_COUNTRIES = [
    # Tier 1 - Major Markets
    {"text": {"type": "plain_text", "text": "🇺🇸 USA - United States"}, "value": "USA"},
    {"text": {"type": "plain_text", "text": "🇬🇧 GBR - United Kingdom"}, "value": "GBR"},
    {"text": {"type": "plain_text", "text": "🇩🇪 DEU - Germany"}, "value": "DEU"},
    {"text": {"type": "plain_text", "text": "🇫🇷 FRA - France"}, "value": "FRA"},
    {"text": {"type": "plain_text", "text": "🇮🇹 ITA - Italy"}, "value": "ITA"},
    {"text": {"type": "plain_text", "text": "🇪🇸 ESP - Spain"}, "value": "ESP"},
    {"text": {"type": "plain_text", "text": "🇯🇵 JPN - Japan"}, "value": "JPN"},
    {"text": {"type": "plain_text", "text": "🇰🇷 KOR - South Korea"}, "value": "KOR"},
    {"text": {"type": "plain_text", "text": "🇨🇦 CAN - Canada"}, "value": "CAN"},
    {"text": {"type": "plain_text", "text": "🇦🇺 AUS - Australia"}, "value": "AUS"},
    {"text": {"type": "plain_text", "text": "🇳🇱 NLD - Netherlands"}, "value": "NLD"},
    {"text": {"type": "plain_text", "text": "🇨🇭 CHE - Switzerland"}, "value": "CHE"},
    {"text": {"type": "plain_text", "text": "🇧🇪 BEL - Belgium"}, "value": "BEL"},
    {"text": {"type": "plain_text", "text": "🇦🇹 AUT - Austria"}, "value": "AUT"},
    {"text": {"type": "plain_text", "text": "🇸🇪 SWE - Sweden"}, "value": "SWE"},
    {"text": {"type": "plain_text", "text": "🇳🇴 NOR - Norway"}, "value": "NOR"},
    {"text": {"type": "plain_text", "text": "🇩🇰 DNK - Denmark"}, "value": "DNK"},
    {"text": {"type": "plain_text", "text": "🇫🇮 FIN - Finland"}, "value": "FIN"},
    {"text": {"type": "plain_text", "text": "🇮🇪 IRL - Ireland"}, "value": "IRL"},
    {"text": {"type": "plain_text", "text": "🇸🇬 SGP - Singapore"}, "value": "SGP"},
    {"text": {"type": "plain_text", "text": "🇳🇿 NZL - New Zealand"}, "value": "NZL"},
    
    # Tier 2 - Growing Markets
    {"text": {"type": "plain_text", "text": "🇧🇷 BRA - Brazil"}, "value": "BRA"},
    {"text": {"type": "plain_text", "text": "🇲🇽 MEX - Mexico"}, "value": "MEX"},
    {"text": {"type": "plain_text", "text": "🇦🇷 ARG - Argentina"}, "value": "ARG"},
    {"text": {"type": "plain_text", "text": "🇨🇱 CHL - Chile"}, "value": "CHL"},
    {"text": {"type": "plain_text", "text": "🇨🇴 COL - Colombia"}, "value": "COL"},
    {"text": {"type": "plain_text", "text": "🇮🇳 IND - India"}, "value": "IND"},
    {"text": {"type": "plain_text", "text": "🇮🇩 IDN - Indonesia"}, "value": "IDN"},
    {"text": {"type": "plain_text", "text": "🇹🇭 THA - Thailand"}, "value": "THA"},
    {"text": {"type": "plain_text", "text": "🇲🇾 MYS - Malaysia"}, "value": "MYS"},
    {"text": {"type": "plain_text", "text": "🇵🇭 PHL - Philippines"}, "value": "PHL"},
    {"text": {"type": "plain_text", "text": "🇻🇳 VNM - Vietnam"}, "value": "VNM"},
    {"text": {"type": "plain_text", "text": "🇹🇷 TUR - Turkey"}, "value": "TUR"},
    {"text": {"type": "plain_text", "text": "🇵🇱 POL - Poland"}, "value": "POL"},
    {"text": {"type": "plain_text", "text": "🇺🇦 UKR - Ukraine"}, "value": "UKR"},
    {"text": {"type": "plain_text", "text": "🇷🇺 RUS - Russia"}, "value": "RUS"},
    {"text": {"type": "plain_text", "text": "🇵🇹 PRT - Portugal"}, "value": "PRT"},
    {"text": {"type": "plain_text", "text": "🇬🇷 GRC - Greece"}, "value": "GRC"},
    {"text": {"type": "plain_text", "text": "🇨🇿 CZE - Czech Republic"}, "value": "CZE"},
    {"text": {"type": "plain_text", "text": "🇭🇺 HUN - Hungary"}, "value": "HUN"},
    {"text": {"type": "plain_text", "text": "🇷🇴 ROU - Romania"}, "value": "ROU"},
    {"text": {"type": "plain_text", "text": "🇿🇦 ZAF - South Africa"}, "value": "ZAF"},
    {"text": {"type": "plain_text", "text": "🇦🇪 ARE - United Arab Emirates"}, "value": "ARE"},
    {"text": {"type": "plain_text", "text": "🇸🇦 SAU - Saudi Arabia"}, "value": "SAU"},
    {"text": {"type": "plain_text", "text": "🇮🇱 ISR - Israel"}, "value": "ISR"},
    
    # Tier 3 - Emerging Markets
    {"text": {"type": "plain_text", "text": "🇵🇪 PER - Peru"}, "value": "PER"},
    {"text": {"type": "plain_text", "text": "🇪🇨 ECU - Ecuador"}, "value": "ECU"},
    {"text": {"type": "plain_text", "text": "🇻🇪 VEN - Venezuela"}, "value": "VEN"},
    {"text": {"type": "plain_text", "text": "🇺🇾 URY - Uruguay"}, "value": "URY"},
    {"text": {"type": "plain_text", "text": "🇵🇾 PRY - Paraguay"}, "value": "PRY"},
    {"text": {"type": "plain_text", "text": "🇨🇷 CRI - Costa Rica"}, "value": "CRI"},
    {"text": {"type": "plain_text", "text": "🇵🇦 PAN - Panama"}, "value": "PAN"},
    {"text": {"type": "plain_text", "text": "🇩🇴 DOM - Dominican Republic"}, "value": "DOM"},
    {"text": {"type": "plain_text", "text": "🇪🇬 EGY - Egypt"}, "value": "EGY"},
    {"text": {"type": "plain_text", "text": "🇲🇦 MAR - Morocco"}, "value": "MAR"},
    {"text": {"type": "plain_text", "text": "🇳🇬 NGA - Nigeria"}, "value": "NGA"},
    {"text": {"type": "plain_text", "text": "🇰🇪 KEN - Kenya"}, "value": "KEN"},
    {"text": {"type": "plain_text", "text": "🇵🇰 PAK - Pakistan"}, "value": "PAK"},
    {"text": {"type": "plain_text", "text": "🇧🇩 BGD - Bangladesh"}, "value": "BGD"},
    {"text": {"type": "plain_text", "text": "🇱🇰 LKA - Sri Lanka"}, "value": "LKA"},
    {"text": {"type": "plain_text", "text": "🇰🇿 KAZ - Kazakhstan"}, "value": "KAZ"},
    {"text": {"type": "plain_text", "text": "🇧🇾 BLR - Belarus"}, "value": "BLR"},
    {"text": {"type": "plain_text", "text": "🇺🇿 UZB - Uzbekistan"}, "value": "UZB"},
    {"text": {"type": "plain_text", "text": "🇦🇿 AZE - Azerbaijan"}, "value": "AZE"},
    {"text": {"type": "plain_text", "text": "🇬🇪 GEO - Georgia"}, "value": "GEO"},
    {"text": {"type": "plain_text", "text": "🇦🇲 ARM - Armenia"}, "value": "ARM"},
    {"text": {"type": "plain_text", "text": "🇭🇰 HKG - Hong Kong"}, "value": "HKG"},
    {"text": {"type": "plain_text", "text": "🇹🇼 TWN - Taiwan"}, "value": "TWN"},
    {"text": {"type": "plain_text", "text": "🇯🇴 JOR - Jordan"}, "value": "JOR"},
    {"text": {"type": "plain_text", "text": "🇱🇧 LBN - Lebanon"}, "value": "LBN"},
    {"text": {"type": "plain_text", "text": "🇶🇦 QAT - Qatar"}, "value": "QAT"},
    {"text": {"type": "plain_text", "text": "🇰🇼 KWT - Kuwait"}, "value": "KWT"},
    {"text": {"type": "plain_text", "text": "🇧🇭 BHR - Bahrain"}, "value": "BHR"},
    {"text": {"type": "plain_text", "text": "🇴🇲 OMN - Oman"}, "value": "OMN"},
    {"text": {"type": "plain_text", "text": "🇧🇬 BGR - Bulgaria"}, "value": "BGR"},
    {"text": {"type": "plain_text", "text": "🇭🇷 HRV - Croatia"}, "value": "HRV"},
    {"text": {"type": "plain_text", "text": "🇸🇰 SVK - Slovakia"}, "value": "SVK"},
    {"text": {"type": "plain_text", "text": "🇸🇮 SVN - Slovenia"}, "value": "SVN"},
    {"text": {"type": "plain_text", "text": "🇱🇹 LTU - Lithuania"}, "value": "LTU"},
    {"text": {"type": "plain_text", "text": "🇱🇻 LVA - Latvia"}, "value": "LVA"},
    {"text": {"type": "plain_text", "text": "🇪🇪 EST - Estonia"}, "value": "EST"},
    {"text": {"type": "plain_text", "text": "🇷🇸 SRB - Serbia"}, "value": "SRB"},
    {"text": {"type": "plain_text", "text": "🇧🇦 BIH - Bosnia and Herzegovina"}, "value": "BIH"},
    {"text": {"type": "plain_text", "text": "🇲🇰 MKD - North Macedonia"}, "value": "MKD"},
    {"text": {"type": "plain_text", "text": "🇦🇱 ALB - Albania"}, "value": "ALB"},
    {"text": {"type": "plain_text", "text": "🇲🇪 MNE - Montenegro"}, "value": "MNE"},
    {"text": {"type": "plain_text", "text": "🇽🇰 XKX - Kosovo"}, "value": "XKX"},
    {"text": {"type": "plain_text", "text": "🇲🇩 MDA - Moldova"}, "value": "MDA"},
    {"text": {"type": "plain_text", "text": "🇮🇸 ISL - Iceland"}, "value": "ISL"},
    {"text": {"type": "plain_text", "text": "🇱🇺 LUX - Luxembourg"}, "value": "LUX"},
    {"text": {"type": "plain_text", "text": "🇲🇹 MLT - Malta"}, "value": "MLT"},
    {"text": {"type": "plain_text", "text": "🇨🇾 CYP - Cyprus"}, "value": "CYP"}
]