# countries.py - Complete country list for AppGrowth bot (All ISO 3166-1 alpha-3 codes)

POPULAR_COUNTRIES = [
    # Tier 1 - Major Markets
    {"text": {"type": "plain_text", "text": "🇺🇸 USA - United States"}, "value": "USA"},
    {"text": {"type": "plain_text", "text": "🇬🇧 GBR - United Kingdom"}, "value": "GBR"},
    {"text": {"type": "plain_text", "text": "🇩🇪 DEU - Germany"}, "value": "DEU"},
    {"text": {"type": "plain_text", "text": "🇫🇷 FRA - France"}, "value": "FRA"},
    {"text": {"type": "plain_text", "text": "🇮🇹 ITA - Italy"}, "value": "ITA"},
    {"text": {"type": "plain_text", "text": "🇪🇸 ESP - Spain"}, "value": "ESP"},
    {"text": {"type": "plain_text", "text": "🇯🇵 JPN - Japan"}, "value": "JPN"},
    {"text": {"type": "plain_text", "text": "🇰🇷 KOR - South Korea"}, "value": "KOR"},
    {"text": {"type": "plain_text", "text": "🇨🇦 CAN - Canada"}, "value": "CAN"},
    {"text": {"type": "plain_text", "text": "🇦🇺 AUS - Australia"}, "value": "AUS"},
    {"text": {"type": "plain_text", "text": "🇳🇱 NLD - Netherlands"}, "value": "NLD"},
    {"text": {"type": "plain_text", "text": "🇨🇭 CHE - Switzerland"}, "value": "CHE"},
    {"text": {"type": "plain_text", "text": "🇧🇪 BEL - Belgium"}, "value": "BEL"},
    {"text": {"type": "plain_text", "text": "🇦🇹 AUT - Austria"}, "value": "AUT"},
    {"text": {"type": "plain_text", "text": "🇸🇪 SWE - Sweden"}, "value": "SWE"},
    {"text": {"type": "plain_text", "text": "🇳🇴 NOR - Norway"}, "value": "NOR"},
    {"text": {"type": "plain_text", "text": "🇩🇰 DNK - Denmark"}, "value": "DNK"},
    {"text": {"type": "plain_text", "text": "🇫🇮 FIN - Finland"}, "value": "FIN"},
    {"text": {"type": "plain_text", "text": "🇮🇪 IRL - Ireland"}, "value": "IRL"},
    {"text": {"type": "plain_text", "text": "🇸🇬 SGP - Singapore"}, "value": "SGP"},
    {"text": {"type": "plain_text", "text": "🇳🇿 NZL - New Zealand"}, "value": "NZL"},

    # Tier 2 - Growing Markets
    {"text": {"type": "plain_text", "text": "🇧🇷 BRA - Brazil"}, "value": "BRA"},
    {"text": {"type": "plain_text", "text": "🇲🇽 MEX - Mexico"}, "value": "MEX"},
    {"text": {"type": "plain_text", "text": "🇦🇷 ARG - Argentina"}, "value": "ARG"},
    {"text": {"type": "plain_text", "text": "🇨🇱 CHL - Chile"}, "value": "CHL"},
    {"text": {"type": "plain_text", "text": "🇨🇴 COL - Colombia"}, "value": "COL"},
    {"text": {"type": "plain_text", "text": "🇮🇳 IND - India"}, "value": "IND"},
    {"text": {"type": "plain_text", "text": "🇮🇩 IDN - Indonesia"}, "value": "IDN"},
    {"text": {"type": "plain_text", "text": "🇹🇭 THA - Thailand"}, "value": "THA"},
    {"text": {"type": "plain_text", "text": "🇲🇾 MYS - Malaysia"}, "value": "MYS"},
    {"text": {"type": "plain_text", "text": "🇵🇭 PHL - Philippines"}, "value": "PHL"},
    {"text": {"type": "plain_text", "text": "🇻🇳 VNM - Vietnam"}, "value": "VNM"},
    {"text": {"type": "plain_text", "text": "🇹🇷 TUR - Turkey"}, "value": "TUR"},
    {"text": {"type": "plain_text", "text": "🇵🇱 POL - Poland"}, "value": "POL"},
    {"text": {"type": "plain_text", "text": "🇺🇦 UKR - Ukraine"}, "value": "UKR"},
    {"text": {"type": "plain_text", "text": "🇷🇺 RUS - Russia"}, "value": "RUS"},
    {"text": {"type": "plain_text", "text": "🇵🇹 PRT - Portugal"}, "value": "PRT"},
    {"text": {"type": "plain_text", "text": "🇬🇷 GRC - Greece"}, "value": "GRC"},
    {"text": {"type": "plain_text", "text": "🇨🇿 CZE - Czech Republic"}, "value": "CZE"},
    {"text": {"type": "plain_text", "text": "🇭🇺 HUN - Hungary"}, "value": "HUN"},
    {"text": {"type": "plain_text", "text": "🇷🇴 ROU - Romania"}, "value": "ROU"},
    {"text": {"type": "plain_text", "text": "🇿🇦 ZAF - South Africa"}, "value": "ZAF"},
    {"text": {"type": "plain_text", "text": "🇦🇪 ARE - United Arab Emirates"}, "value": "ARE"},
    {"text": {"type": "plain_text", "text": "🇸🇦 SAU - Saudi Arabia"}, "value": "SAU"},
    {"text": {"type": "plain_text", "text": "🇮🇱 ISR - Israel"}, "value": "ISR"},

    # Tier 3 - Emerging Markets
    {"text": {"type": "plain_text", "text": "🇵🇪 PER - Peru"}, "value": "PER"},
    {"text": {"type": "plain_text", "text": "🇪🇨 ECU - Ecuador"}, "value": "ECU"},
    {"text": {"type": "plain_text", "text": "🇻🇪 VEN - Venezuela"}, "value": "VEN"},
    {"text": {"type": "plain_text", "text": "🇺🇾 URY - Uruguay"}, "value": "URY"},
    {"text": {"type": "plain_text", "text": "🇵🇾 PRY - Paraguay"}, "value": "PRY"},
    {"text": {"type": "plain_text", "text": "🇨🇷 CRI - Costa Rica"}, "value": "CRI"},
    {"text": {"type": "plain_text", "text": "🇵🇦 PAN - Panama"}, "value": "PAN"},
    {"text": {"type": "plain_text", "text": "🇩🇴 DOM - Dominican Republic"}, "value": "DOM"},
    {"text": {"type": "plain_text", "text": "🇪🇬 EGY - Egypt"}, "value": "EGY"},
    {"text": {"type": "plain_text", "text": "🇲🇦 MAR - Morocco"}, "value": "MAR"},
    {"text": {"type": "plain_text", "text": "🇳🇬 NGA - Nigeria"}, "value": "NGA"},
    {"text": {"type": "plain_text", "text": "🇰🇪 KEN - Kenya"}, "value": "KEN"},
    {"text": {"type": "plain_text", "text": "🇵🇰 PAK - Pakistan"}, "value": "PAK"},
    {"text": {"type": "plain_text", "text": "🇧🇩 BGD - Bangladesh"}, "value": "BGD"},
    {"text": {"type": "plain_text", "text": "🇱🇰 LKA - Sri Lanka"}, "value": "LKA"},
    {"text": {"type": "plain_text", "text": "🇰🇿 KAZ - Kazakhstan"}, "value": "KAZ"},
    {"text": {"type": "plain_text", "text": "🇧🇾 BLR - Belarus"}, "value": "BLR"},
    {"text": {"type": "plain_text", "text": "🇺🇿 UZB - Uzbekistan"}, "value": "UZB"},
    {"text": {"type": "plain_text", "text": "🇦🇿 AZE - Azerbaijan"}, "value": "AZE"},
    {"text": {"type": "plain_text", "text": "🇬🇪 GEO - Georgia"}, "value": "GEO"},
    {"text": {"type": "plain_text", "text": "🇦🇲 ARM - Armenia"}, "value": "ARM"},
    {"text": {"type": "plain_text", "text": "🇭🇰 HKG - Hong Kong"}, "value": "HKG"},
    {"text": {"type": "plain_text", "text": "🇹🇼 TWN - Taiwan"}, "value": "TWN"},
    {"text": {"type": "plain_text", "text": "🇯🇴 JOR - Jordan"}, "value": "JOR"},
    {"text": {"type": "plain_text", "text": "🇱🇧 LBN - Lebanon"}, "value": "LBN"},
    {"text": {"type": "plain_text", "text": "🇶🇦 QAT - Qatar"}, "value": "QAT"},
    {"text": {"type": "plain_text", "text": "🇰🇼 KWT - Kuwait"}, "value": "KWT"},
    {"text": {"type": "plain_text", "text": "🇧🇭 BHR - Bahrain"}, "value": "BHR"},
    {"text": {"type": "plain_text", "text": "🇴🇲 OMN - Oman"}, "value": "OMN"},
    {"text": {"type": "plain_text", "text": "🇧🇬 BGR - Bulgaria"}, "value": "BGR"},
    {"text": {"type": "plain_text", "text": "🇭🇷 HRV - Croatia"}, "value": "HRV"},
    {"text": {"type": "plain_text", "text": "🇸🇰 SVK - Slovakia"}, "value": "SVK"},
    {"text": {"type": "plain_text", "text": "🇸🇮 SVN - Slovenia"}, "value": "SVN"},
    {"text": {"type": "plain_text", "text": "🇱🇹 LTU - Lithuania"}, "value": "LTU"},
    {"text": {"type": "plain_text", "text": "🇱🇻 LVA - Latvia"}, "value": "LVA"},
    {"text": {"type": "plain_text", "text": "🇪🇪 EST - Estonia"}, "value": "EST"},
    {"text": {"type": "plain_text", "text": "🇷🇸 SRB - Serbia"}, "value": "SRB"},
    {"text": {"type": "plain_text", "text": "🇧🇦 BIH - Bosnia and Herzegovina"}, "value": "BIH"},
    {"text": {"type": "plain_text", "text": "🇲🇰 MKD - North Macedonia"}, "value": "MKD"},
    {"text": {"type": "plain_text", "text": "🇦🇱 ALB - Albania"}, "value": "ALB"},
    {"text": {"type": "plain_text", "text": "🇲🇪 MNE - Montenegro"}, "value": "MNE"},
    {"text": {"type": "plain_text", "text": "🇽🇰 XKX - Kosovo"}, "value": "XKX"},
    {"text": {"type": "plain_text", "text": "🇲🇩 MDA - Moldova"}, "value": "MDA"},
    {"text": {"type": "plain_text", "text": "🇮🇸 ISL - Iceland"}, "value": "ISL"},
    {"text": {"type": "plain_text", "text": "🇱🇺 LUX - Luxembourg"}, "value": "LUX"},
    {"text": {"type": "plain_text", "text": "🇲🇹 MLT - Malta"}, "value": "MLT"},
    {"text": {"type": "plain_text", "text": "🇨🇾 CYP - Cyprus"}, "value": "CYP"},

    # Additional Countries (Alphabetically sorted by code)
    {"text": {"type": "plain_text", "text": "🇦🇫 AFG - Afghanistan"}, "value": "AFG"},
    {"text": {"type": "plain_text", "text": "🇦🇬 ATG - Antigua and Barbuda"}, "value": "ATG"},
    {"text": {"type": "plain_text", "text": "🇦🇮 AIA - Anguilla"}, "value": "AIA"},
    {"text": {"type": "plain_text", "text": "🇦🇴 AGO - Angola"}, "value": "AGO"},
    {"text": {"type": "plain_text", "text": "🇦🇶 ATA - Antarctica"}, "value": "ATA"},
    {"text": {"type": "plain_text", "text": "🇦🇸 ASM - American Samoa"}, "value": "ASM"},
    {"text": {"type": "plain_text", "text": "🇦🇼 ABW - Aruba"}, "value": "ABW"},
    {"text": {"type": "plain_text", "text": "🇦🇽 ALA - Åland Islands"}, "value": "ALA"},
    {"text": {"type": "plain_text", "text": "🇧🇧 BRB - Barbados"}, "value": "BRB"},
    {"text": {"type": "plain_text", "text": "🇧🇩 BGD - Bangladesh"}, "value": "BGD"},
    {"text": {"type": "plain_text", "text": "🇧🇫 BFA - Burkina Faso"}, "value": "BFA"},
    {"text": {"type": "plain_text", "text": "🇧🇮 BDI - Burundi"}, "value": "BDI"},
    {"text": {"type": "plain_text", "text": "🇧🇯 BEN - Benin"}, "value": "BEN"},
    {"text": {"type": "plain_text", "text": "🇧🇱 BLM - Saint Barthélemy"}, "value": "BLM"},
    {"text": {"type": "plain_text", "text": "🇧🇲 BMU - Bermuda"}, "value": "BMU"},
    {"text": {"type": "plain_text", "text": "🇧🇳 BRN - Brunei"}, "value": "BRN"},
    {"text": {"type": "plain_text", "text": "🇧🇴 BOL - Bolivia"}, "value": "BOL"},
    {"text": {"type": "plain_text", "text": "🇧🇶 BES - Bonaire, Sint Eustatius and Saba"}, "value": "BES"},
    {"text": {"type": "plain_text", "text": "🇧🇸 BHS - Bahamas"}, "value": "BHS"},
    {"text": {"type": "plain_text", "text": "🇧🇹 BTN - Bhutan"}, "value": "BTN"},
    {"text": {"type": "plain_text", "text": "🇧🇻 BVT - Bouvet Island"}, "value": "BVT"},
    {"text": {"type": "plain_text", "text": "🇧🇼 BWA - Botswana"}, "value": "BWA"},
    {"text": {"type": "plain_text", "text": "🇧🇿 BLZ - Belize"}, "value": "BLZ"},
    {"text": {"type": "plain_text", "text": "🇨🇨 CCK - Cocos (Keeling) Islands"}, "value": "CCK"},
    {"text": {"type": "plain_text", "text": "🇨🇩 COD - DR Congo"}, "value": "COD"},
    {"text": {"type": "plain_text", "text": "🇨🇫 CAF - Central African Republic"}, "value": "CAF"},
    {"text": {"type": "plain_text", "text": "🇨🇬 COG - Congo"}, "value": "COG"},
    {"text": {"type": "plain_text", "text": "🇨🇮 CIV - Côte d'Ivoire"}, "value": "CIV"},
    {"text": {"type": "plain_text", "text": "🇨🇰 COK - Cook Islands"}, "value": "COK"},
    {"text": {"type": "plain_text", "text": "🇨🇲 CMR - Cameroon"}, "value": "CMR"},
    {"text": {"type": "plain_text", "text": "🇨🇳 CHN - China"}, "value": "CHN"},
    {"text": {"type": "plain_text", "text": "🇨🇺 CUB - Cuba"}, "value": "CUB"},
    {"text": {"type": "plain_text", "text": "🇨🇻 CPV - Cabo Verde"}, "value": "CPV"},
    {"text": {"type": "plain_text", "text": "🇨🇼 CUW - Curaçao"}, "value": "CUW"},
    {"text": {"type": "plain_text", "text": "🇨🇽 CXR - Christmas Island"}, "value": "CXR"},
    {"text": {"type": "plain_text", "text": "🇩🇯 DJI - Djibouti"}, "value": "DJI"},
    {"text": {"type": "plain_text", "text": "🇩🇲 DMA - Dominica"}, "value": "DMA"},
    {"text": {"type": "plain_text", "text": "🇩🇿 DZA - Algeria"}, "value": "DZA"},
    {"text": {"type": "plain_text", "text": "🇪🇷 ERI - Eritrea"}, "value": "ERI"},
    {"text": {"type": "plain_text", "text": "🇪🇹 ETH - Ethiopia"}, "value": "ETH"},
    {"text": {"type": "plain_text", "text": "🇫🇯 FJI - Fiji"}, "value": "FJI"},
    {"text": {"type": "plain_text", "text": "🇫🇰 FLK - Falkland Islands"}, "value": "FLK"},
    {"text": {"type": "plain_text", "text": "🇫🇲 FSM - Micronesia"}, "value": "FSM"},
    {"text": {"type": "plain_text", "text": "🇫🇴 FRO - Faroe Islands"}, "value": "FRO"},
    {"text": {"type": "plain_text", "text": "🇬🇦 GAB - Gabon"}, "value": "GAB"},
    {"text": {"type": "plain_text", "text": "🇬🇩 GRD - Grenada"}, "value": "GRD"},
    {"text": {"type": "plain_text", "text": "🇬🇫 GUF - French Guiana"}, "value": "GUF"},
    {"text": {"type": "plain_text", "text": "🇬🇬 GGY - Guernsey"}, "value": "GGY"},
    {"text": {"type": "plain_text", "text": "🇬🇭 GHA - Ghana"}, "value": "GHA"},
    {"text": {"type": "plain_text", "text": "🇬🇮 GIB - Gibraltar"}, "value": "GIB"},
    {"text": {"type": "plain_text", "text": "🇬🇱 GRL - Greenland"}, "value": "GRL"},
    {"text": {"type": "plain_text", "text": "🇬🇲 GMB - Gambia"}, "value": "GMB"},
    {"text": {"type": "plain_text", "text": "🇬🇳 GIN - Guinea"}, "value": "GIN"},
    {"text": {"type": "plain_text", "text": "🇬🇵 GLP - Guadeloupe"}, "value": "GLP"},
    {"text": {"type": "plain_text", "text": "🇬🇶 GNQ - Equatorial Guinea"}, "value": "GNQ"},
    {"text": {"type": "plain_text", "text": "🇬🇸 SGS - South Georgia and the South Sandwich Islands"}, "value": "SGS"},
    {"text": {"type": "plain_text", "text": "🇬🇹 GTM - Guatemala"}, "value": "GTM"},
    {"text": {"type": "plain_text", "text": "🇬🇺 GUM - Guam"}, "value": "GUM"},
    {"text": {"type": "plain_text", "text": "🇬🇼 GNB - Guinea-Bissau"}, "value": "GNB"},
    {"text": {"type": "plain_text", "text": "🇬🇾 GUY - Guyana"}, "value": "GUY"},
    {"text": {"type": "plain_text", "text": "🇭🇲 HMD - Heard Island and McDonald Islands"}, "value": "HMD"},
    {"text": {"type": "plain_text", "text": "🇭🇳 HND - Honduras"}, "value": "HND"},
    {"text": {"type": "plain_text", "text": "🇭🇹 HTI - Haiti"}, "value": "HTI"},
    {"text": {"type": "plain_text", "text": "🇮🇴 IOT - British Indian Ocean Territory"}, "value": "IOT"},
    {"text": {"type": "plain_text", "text": "🇮🇶 IRQ - Iraq"}, "value": "IRQ"},
    {"text": {"type": "plain_text", "text": "🇮🇷 IRN - Iran"}, "value": "IRN"},
    {"text": {"type": "plain_text", "text": "🇯🇪 JEY - Jersey"}, "value": "JEY"},
    {"text": {"type": "plain_text", "text": "🇯🇲 JAM - Jamaica"}, "value": "JAM"},
    {"text": {"type": "plain_text", "text": "🇰🇬 KGZ - Kyrgyzstan"}, "value": "KGZ"},
    {"text": {"type": "plain_text", "text": "🇰🇭 KHM - Cambodia"}, "value": "KHM"},
    {"text": {"type": "plain_text", "text": "🇰🇮 KIR - Kiribati"}, "value": "KIR"},
    {"text": {"type": "plain_text", "text": "🇰🇲 COM - Comoros"}, "value": "COM"},
    {"text": {"type": "plain_text", "text": "🇰🇳 KNA - Saint Kitts and Nevis"}, "value": "KNA"},
    {"text": {"type": "plain_text", "text": "🇰🇵 PRK - North Korea"}, "value": "PRK"},
    {"text": {"type": "plain_text", "text": "🇰🇾 CYM - Cayman Islands"}, "value": "CYM"},
    {"text": {"type": "plain_text", "text": "🇱🇦 LAO - Laos"}, "value": "LAO"},
    {"text": {"type": "plain_text", "text": "🇱🇨 LCA - Saint Lucia"}, "value": "LCA"},
    {"text": {"type": "plain_text", "text": "🇱🇮 LIE - Liechtenstein"}, "value": "LIE"},
    {"text": {"type": "plain_text", "text": "🇱🇷 LBR - Liberia"}, "value": "LBR"},
    {"text": {"type": "plain_text", "text": "🇱🇸 LSO - Lesotho"}, "value": "LSO"},
    {"text": {"type": "plain_text", "text": "🇱🇾 LBY - Libya"}, "value": "LBY"},
    {"text": {"type": "plain_text", "text": "🇲🇨 MCO - Monaco"}, "value": "MCO"},
    {"text": {"type": "plain_text", "text": "🇲🇫 MAF - Saint Martin"}, "value": "MAF"},
    {"text": {"type": "plain_text", "text": "🇲🇬 MDG - Madagascar"}, "value": "MDG"},
    {"text": {"type": "plain_text", "text": "🇲🇭 MHL - Marshall Islands"}, "value": "MHL"},
    {"text": {"type": "plain_text", "text": "🇲🇱 MLI - Mali"}, "value": "MLI"},
    {"text": {"type": "plain_text", "text": "🇲🇲 MMR - Myanmar"}, "value": "MMR"},
    {"text": {"type": "plain_text", "text": "🇲🇳 MNG - Mongolia"}, "value": "MNG"},
    {"text": {"type": "plain_text", "text": "🇲🇴 MAC - Macao"}, "value": "MAC"},
    {"text": {"type": "plain_text", "text": "🇲🇵 MNP - Northern Mariana Islands"}, "value": "MNP"},
    {"text": {"type": "plain_text", "text": "🇲🇶 MTQ - Martinique"}, "value": "MTQ"},
    {"text": {"type": "plain_text", "text": "🇲🇷 MRT - Mauritania"}, "value": "MRT"},
    {"text": {"type": "plain_text", "text": "🇲🇸 MSR - Montserrat"}, "value": "MSR"},
    {"text": {"type": "plain_text", "text": "🇲🇺 MUS - Mauritius"}, "value": "MUS"},
    {"text": {"type": "plain_text", "text": "🇲🇻 MDV - Maldives"}, "value": "MDV"},
    {"text": {"type": "plain_text", "text": "🇲🇼 MWI - Malawi"}, "value": "MWI"},
    {"text": {"type": "plain_text", "text": "🇲🇿 MOZ - Mozambique"}, "value": "MOZ"},
    {"text": {"type": "plain_text", "text": "🇳🇦 NAM - Namibia"}, "value": "NAM"},
    {"text": {"type": "plain_text", "text": "🇳🇨 NCL - New Caledonia"}, "value": "NCL"},
    {"text": {"type": "plain_text", "text": "🇳🇪 NER - Niger"}, "value": "NER"},
    {"text": {"type": "plain_text", "text": "🇳🇫 NFK - Norfolk Island"}, "value": "NFK"},
    {"text": {"type": "plain_text", "text": "🇳🇮 NIC - Nicaragua"}, "value": "NIC"},
    {"text": {"type": "plain_text", "text": "🇳🇵 NPL - Nepal"}, "value": "NPL"},
    {"text": {"type": "plain_text", "text": "🇳🇷 NRU - Nauru"}, "value": "NRU"},
    {"text": {"type": "plain_text", "text": "🇳🇺 NIU - Niue"}, "value": "NIU"},
    {"text": {"type": "plain_text", "text": "🇵🇫 PYF - French Polynesia"}, "value": "PYF"},
    {"text": {"type": "plain_text", "text": "🇵🇬 PNG - Papua New Guinea"}, "value": "PNG"},
    {"text": {"type": "plain_text", "text": "🇵🇲 SPM - Saint Pierre and Miquelon"}, "value": "SPM"},
    {"text": {"type": "plain_text", "text": "🇵🇳 PCN - Pitcairn Islands"}, "value": "PCN"},
    {"text": {"type": "plain_text", "text": "🇵🇷 PRI - Puerto Rico"}, "value": "PRI"},
    {"text": {"type": "plain_text", "text": "🇵🇸 PSE - Palestine"}, "value": "PSE"},
    {"text": {"type": "plain_text", "text": "🇵🇼 PLW - Palau"}, "value": "PLW"},
    {"text": {"type": "plain_text", "text": "🇷🇪 REU - Réunion"}, "value": "REU"},
    {"text": {"type": "plain_text", "text": "🇷🇼 RWA - Rwanda"}, "value": "RWA"},
    {"text": {"type": "plain_text", "text": "🇸🇧 SLB - Solomon Islands"}, "value": "SLB"},
    {"text": {"type": "plain_text", "text": "🇸🇨 SYC - Seychelles"}, "value": "SYC"},
    {"text": {"type": "plain_text", "text": "🇸🇩 SDN - Sudan"}, "value": "SDN"},
    {"text": {"type": "plain_text", "text": "🇸🇭 SHN - Saint Helena, Ascension and Tristan da Cunha"}, "value": "SHN"},
    {"text": {"type": "plain_text", "text": "🇸🇯 SJM - Svalbard and Jan Mayen"}, "value": "SJM"},
    {"text": {"type": "plain_text", "text": "🇸🇱 SLE - Sierra Leone"}, "value": "SLE"},
    {"text": {"type": "plain_text", "text": "🇸🇲 SMR - San Marino"}, "value": "SMR"},
    {"text": {"type": "plain_text", "text": "🇸🇳 SEN - Senegal"}, "value": "SEN"},
    {"text": {"type": "plain_text", "text": "🇸🇴 SOM - Somalia"}, "value": "SOM"},
    {"text": {"type": "plain_text", "text": "🇸🇷 SUR - Suriname"}, "value": "SUR"},
    {"text": {"type": "plain_text", "text": "🇸🇸 SSD - South Sudan"}, "value": "SSD"},
    {"text": {"type": "plain_text", "text": "🇸🇹 STP - São Tomé and Príncipe"}, "value": "STP"},
    {"text": {"type": "plain_text", "text": "🇸🇻 SLV - El Salvador"}, "value": "SLV"},
    {"text": {"type": "plain_text", "text": "🇸🇽 SXM - Sint Maarten"}, "value": "SXM"},
    {"text": {"type": "plain_text", "text": "🇸🇾 SYR - Syria"}, "value": "SYR"},
    {"text": {"type": "plain_text", "text": "🇸🇿 SWZ - Eswatini"}, "value": "SWZ"},
    {"text": {"type": "plain_text", "text": "🇹🇨 TCA - Turks and Caicos Islands"}, "value": "TCA"},
    {"text": {"type": "plain_text", "text": "🇹🇩 TCD - Chad"}, "value": "TCD"},
    {"text": {"type": "plain_text", "text": "🇹🇫 ATF - French Southern Territories"}, "value": "ATF"},
    {"text": {"type": "plain_text", "text": "🇹🇬 TGO - Togo"}, "value": "TGO"},
    {"text": {"type": "plain_text", "text": "🇹🇯 TJK - Tajikistan"}, "value": "TJK"},
    {"text": {"type": "plain_text", "text": "🇹🇰 TKL - Tokelau"}, "value": "TKL"},
    {"text": {"type": "plain_text", "text": "🇹🇱 TLS - Timor-Leste"}, "value": "TLS"},
    {"text": {"type": "plain_text", "text": "🇹🇲 TKM - Turkmenistan"}, "value": "TKM"},
    {"text": {"type": "plain_text", "text": "🇹🇳 TUN - Tunisia"}, "value": "TUN"},
    {"text": {"type": "plain_text", "text": "🇹🇴 TON - Tonga"}, "value": "TON"},
    {"text": {"type": "plain_text", "text": "🇹🇹 TTO - Trinidad and Tobago"}, "value": "TTO"},
    {"text": {"type": "plain_text", "text": "🇹🇻 TUV - Tuvalu"}, "value": "TUV"},
    {"text": {"type": "plain_text", "text": "🇹🇿 TZA - Tanzania"}, "value": "TZA"},
    {"text": {"type": "plain_text", "text": "🇺🇬 UGA - Uganda"}, "value": "UGA"},
    {"text": {"type": "plain_text", "text": "🇺🇲 UMI - U.S. Minor Outlying Islands"}, "value": "UMI"},
    {"text": {"type": "plain_text", "text": "🇻🇦 VAT - Vatican City"}, "value": "VAT"},
    {"text": {"type": "plain_text", "text": "🇻🇨 VCT - Saint Vincent and the Grenadines"}, "value": "VCT"},
    {"text": {"type": "plain_text", "text": "🇻🇬 VGB - British Virgin Islands"}, "value": "VGB"},
    {"text": {"type": "plain_text", "text": "🇻🇮 VIR - U.S. Virgin Islands"}, "value": "VIR"},
    {"text": {"type": "plain_text", "text": "🇻🇺 VUT - Vanuatu"}, "value": "VUT"},
    {"text": {"type": "plain_text", "text": "🇼🇫 WLF - Wallis and Futuna"}, "value": "WLF"},
    {"text": {"type": "plain_text", "text": "🇼🇸 WSM - Samoa"}, "value": "WSM"},
    {"text": {"type": "plain_text", "text": "🇾🇪 YEM - Yemen"}, "value": "YEM"},
    {"text": {"type": "plain_text", "text": "🇾🇹 MYT - Mayotte"}, "value": "MYT"},
    {"text": {"type": "plain_text", "text": "🇿🇲 ZMB - Zambia"}, "value": "ZMB"},
    {"text": {"type": "plain_text", "text": "🇿🇼 ZWE - Zimbabwe"}, "value": "ZWE"},
]
